- name: re-install everything
  hosts: localhost
  tasks:
    - debug:
        msg: "Erasing all VMs and re-installing openshift"

- import_playbook: ovirt-vm-uninstall.yaml


- import_playbook: ovirt-vm-infra.yaml

- import_playbook: openshift-install.yaml
